var GAME_LEVELS = [
  ["  x                                                                          x  ",
   "  x                                                                          x  ",
   "  x                                                                          x  ",
   "  x                                                                          x  ",
   "  x         o                                                                x  ",
   "  x                                                                          x  ",
   "  xxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxx         x  ",
   "  x        x           x              x  o  x                 x              x  ",
   "  x        x =         x              x     x                 x  o      xxxxxx  ",
   "  x        x           x              xxxxxxx                 x              x  ",
   "  x        x    o      x                                      xxxxxx         x  ",
   "  x        x           x                                      x           o  x  ",
   "  x        xxxxxxxxxxxxx                       o              x              x  ",
   "  x                                                           x         xxxxxx  ",
   "  x         |         |            o        xxxxxxx           x  o           x  ",
   "  x              B                                            x              x  ",
   "  x                             xxxxxxx                       xxxxxx       = x  ",
   "  x                                                                          x  ",
   "  x  @                                                                       x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                "],

  ["  x                 x                                                        x  ",
   "  x                 x                                                        x  ",
   "  x                 x                                                        x  ",
   "  x                 x                                                        x  ",
   "  x                 x                                                   o    x  ",
   "  x                 x                                                        x  ",
   "  x       B         x                              xxxxxxxxx     xxxxxxxxxxxxx  ",
   "  x @               x                                      x     x           x  ",
   "  xxxxxxxxxxxx      x                 xxxxxxxxxx         o x     x           x  ",
   "  x                 x                          x           x     x           x  ",
   "  x              =  x             o            x        xxxx     x      o    x  ",
   "  x                 x                          x           x     x           x  ",
   "  x                 x          xxxxxxx         xxxx        x     x    xxxx   x  ",
   "  x  =              x                          x         o x                 x  ",
   "  x                 x                          x           x                 x  ",
   "  x                 x                          xxxxxxxxxxxxx     xxxxxxxxxxxxx  ",
   "  x       xxxxxxxxxxxxxxxxxxxxxx               x                             x  ",
   "  x                 x          x               x             =               x  ",
   "  x                 x    |     x               x                             x  ",
   "  x               = x          x               x       xxxxxxxxxxxxxxx       x  ",
   "  x                 x          xxxxxxx         x                             x  ",
   "  x      o          x                          x              o              x  ",
   "  x                 x                          x                             x  ",
   "  x    xxxxx        x                  xxxxxxxxx       |  xxxxxxxxx |        x  ",
   "  x                                    x    o                                x  ",
   "  x                                    x                                     x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                "],

    ["  xxxxxxxxxxxxxxxxxxxxxx                                                     x  ",
     "  x                    x                                                     x  ",
     "  x              |     x    o                                                x  ",
     "  x                    x                              =                      x  ",
     "  x        x           xxxxxxxxxx              xxxxxxxxxxxxxxxx              x  ",
     "  x        x             |      x       B      x  o           x              x  ",
     "  x     xxxx                    x              x              x       =      x  ",
     "  xo       x          o         x   xxxxxxxx   xxxxxx                        x  ",
     "  x        x                    x              x                             x  ",
     "  xxxx     x                    x       @      x                             x  ",
     "  x        x     xxxxxxxxxx     xxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxx  ",
     "  x        x                                   x       xxxxx                 x  ",
     "  x     xxxx                            o      x                             x  ",
     "  xo       x                                   x                             x  ",
     "  x        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx       =      x  ",
     "  xxxx                       |                                               x  ",
     "  x                o                  o                                      x  ",
     "  x                                                 |                        x  ",
     "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
     "                                                                                "],

     ["  x                        x  ",
      "  x   x   x  x  x   x  x   x  ",
      "  x   x   x  x  xx  x  x   x  ",
      "  x   x   x  x  x x x  x   x  ",
      "  x   x x x  x  x x x  x   x  ",
      "  x   xx xx  x  x  xx      x  ",
      "  x   x   x  x  x   x  x   x  ",
      "  x   o   o        o   o   x  ",
      "  x            @           x  ",
      "  xxxxxxxxxxxxxxxxxxxxxxxxxx  ",
      "                                                 "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
